services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mlabs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/mlabs_db
    ports:
      - "5143:5143"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
